"""
rydnr/basics/pytorch/application/basics_pytorch_app.py

This file defines the BasicsPytorchApp class.

Copyright (C) 2023-today rydnr's https://github.com/rydnr/basics-pytorch

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import asyncio
from pythoneda.application import PythonEDA


class BasicsPytorchApp(PythonEDA):
    """
    Runs the BasicsPytorch PythonEDA app.

    Class name: BasicsPytorchApp

    Responsibilities:
        - Runs the Basics-Pytorch application.

    Collaborators:
        - Command-line handlers from rydnr.basics.pytorch.infrastructure.cli
    """

    def __init__(self):
        """
        Creates a new BasicsPytorchApp instance.
        """
        # basics_pytorch_banner is automatically generated by rydnr/basics-pytorch/nix's flake.
        try:
            from rydnr.basics.pytorch.application.basics_pytorch_banner import (
                BasicsPytorchBanner,
            )

            banner = BasicsPytorchBanner()
        except ImportError:
            banner = None

        super().__init__(banner, __file__)


if __name__ == "__main__":
    asyncio.run(
        NixFlakeToGraphviz.main("rydnr.basics.pytorch.application.BasicsPytorchApp")
    )
